# Generated by Django 4.2.7 on 2024-02-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hodimlar',
            name='vaqt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hodimlar',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
