# Generated by Django 4.2.7 on 2024-02-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hodimlar_vaqt_alter_hodimlar_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('vaqt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hodimlar',
            name='vaqt',
        ),
    ]
