# Generated by Django 4.2.7 on 2024-02-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_habarlar_hodim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habarlar',
            name='vaqt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
