# Generated by Django 4.2.7 on 2024-02-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_habarlar_vaqt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habarlar',
            name='hodim',
        ),
        migrations.AddField(
            model_name='habarlar',
            name='hodim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.hodimlar'),
        ),
    ]
