# Generated by Django 4.2.7 on 2024-02-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_habarlar_hodim_habarlar_hodim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habarlar',
            name='vaqt',
            field=models.DateTimeField(null=True),
        ),
    ]
