# Generated by Django 4.2.7 on 2024-02-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_habarlar_vaqt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habarlar',
            name='hodim',
        ),
        migrations.AddField(
            model_name='habarlar',
            name='hodim',
            field=models.ManyToManyField(null=True, to='main_app.hodimlar'),
        ),
    ]
